#!/bin/bash

##############################################################################
# Agent Skills - Skill 打标脚本
#
# 用法:
#   ./scripts/tag_skill.sh <skill-name> <version>
#
# 示例:
#   ./scripts/tag_skill.sh mermaid 1.0.0
#
# 功能:
#   1. 验证 skill 符合规范
#   2. 创建 git tag（格式: <skill-name>-v<version>）
#   3. 推送 tag 到远程仓库（触发 GitHub Action）
#   4. 支持批量打标
##############################################################################

set -e
set -u

# 引入工具库
source "$(dirname "$0")/utils.sh"

# 全局变量
TAGS_CREATED=()
TAGS_FAILED=()

# 检查 Git 状态
check_git_status() {
  # 检查是否在 git 仓库中
  if ! git rev-parse --git-dir > /dev/null 2>&1; then
    log_error "当前目录不是 Git 仓库"
  fi

  # 检查是否有未提交的更改
  if [ -n "$(git status --porcelain)" ]; then
    log_warning "检测到未提交的更改"
    echo ""
    git status --short
    echo ""
    echo "建议先提交更改："
    echo "  git add ."
    echo "  git commit -m \"feat(skill): update skill\""
    echo ""
    read -p "是否继续？ [y/N] " -n 1 -r
    echo ""
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
      exit 1
    fi
  fi
}

# 为单个 skill 创建 tag
create_tag_for_skill() {
  local skill_name=$1
  local version=$2
  local tag="${skill_name}-v${version}"

  log_step "处理 skill: $skill_name"

  # 1. 验证 skill 存在
  if ! skill_exists "$skill_name"; then
    log_error "Skill 不存在: $skill_name"
    TAGS_FAILED+=("$skill_name")
    return 1
  fi

  # 2. 验证版本号格式
  validate_version "$version"

  # 3. 运行验证脚本
  log_step "验证 skill"
  if ! ./scripts/validate_skill.sh "$skill_name" > /dev/null 2>&1; then
    log_error "Skill 验证失败: $skill_name"
    log_error "请运行: ./scripts/validate_skill.sh $skill_name"
    TAGS_FAILED+=("$skill_name")
    return 1
  fi
  log_success "验证通过"

  # 4. 检查 tag 是否已存在
  if git rev-parse "$tag" > /dev/null 2>&1; then
    log_error "Tag 已存在: $tag"
    echo "如需重新创建，请先删除："
    echo "  git tag -d $tag"
    echo "  git push origin :refs/tags/$tag"
    TAGS_FAILED+=("$skill_name")
    return 1
  fi

  # 5. 创建 tag
  log_step "创建 tag: $tag"
  local display_name=$(get_skill_config "$skill_name" "displayName")
  local description=$(get_skill_config "$skill_name" "description")

  git tag -a "$tag" -m "Release $display_name v$version

$description

Generated by tag_skill.sh"

  log_success "Tag 创建成功"

  # 6. 推送 tag
  log_step "推送 tag 到远程"
  if git push origin "$tag" > /dev/null 2>&1; then
    log_success "Tag 推送成功（GitHub Action 将自动创建 Release）"
    TAGS_CREATED+=("$tag")
  else
    log_error "Tag 推送失败"
    TAGS_FAILED+=("$skill_name")
    return 1
  fi

  echo ""
}

# 显示完成信息
show_completion() {
  echo ""
  echo "=================================="
  log_step "操作完成"
  echo "=================================="
  echo ""

  if [ ${#TAGS_CREATED[@]} -gt 0 ]; then
    echo "✅ 成功创建的 tags (${#TAGS_CREATED[@]}):"
    for tag in "${TAGS_CREATED[@]}"; do
      echo "   $tag"
    done
    echo ""
  fi

  if [ ${#TAGS_FAILED[@]} -gt 0 ]; then
    echo "❌ 失败的 skills (${#TAGS_FAILED[@]}):"
    for skill in "${TAGS_FAILED[@]}"; do
      echo "   $skill"
    done
    echo ""
  fi

  if [ ${#TAGS_CREATED[@]} -gt 0 ]; then
    echo "📌 下一步:"
    echo ""
    echo "1. GitHub Actions 将自动创建 Release"
    echo "2. 访问以下链接查看 Release:"
    local repo_url=$(git remote get-url origin | sed 's/\.git$//' | sed 's/git@github.com:/https:\/\/github.com\//')
    echo "   $repo_url/releases"
    echo ""
    echo "3. 用户可以使用以下命令安装 skill:"
    local repo_owner=$(jq -r ".repository.owner" skills.json)
    local repo_name=$(jq -r ".repository.repo" skills.json)
    for tag in "${TAGS_CREATED[@]}"; do
      local skill_name=$(echo "$tag" | sed 's/-v.*//')
      echo "   npx skills add $repo_owner/$repo_name --skill $skill_name"
    done
  fi

  echo ""
  echo "=================================="
}

# 批量打标（从 skills.json）
batch_tag() {
  local version=$1

  log_step "批量打标模式"
  log_warning "将为所有 skills 创建 tag，版本: v$version"
  echo ""

  read -p "确认继续？ [y/N] " -n 1 -r
  echo ""
  if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    exit 1
  fi

  local all_skills=$(get_all_skills)
  while IFS= read -r skill_name; do
    create_tag_for_skill "$skill_name" "$version"
  done <<< "$all_skills"
}

# 主函数
main() {
  echo "=================================="
  echo "🏷️  Agent Skills 打标工具"
  echo "=================================="
  echo ""

  # 检查 Git 状态
  check_git_status

  # 检查参数
  if [ $# -eq 2 ]; then
    # 单个 skill 打标
    local skill_name=$1
    local version=$2

    create_tag_for_skill "$skill_name" "$version"
    show_completion
  elif [ $# -eq 1 ] && [ "$1" == "--all" ]; then
    # 批量打标
    echo "请输入版本号（例如: 1.0.0）:"
    read -r version
    validate_version "$version"
    batch_tag "$version"
    show_completion
  else
    echo "用法: $0 <skill-name> <version>"
    echo ""
    echo "示例:"
    echo "  $0 mermaid 1.0.0           # 为单个 skill 打标"
    echo "  $0 --all                   # 批量打标（交互式输入版本）"
    echo ""
    echo "生成的 tag 格式: <skill-name>-v<version>"
    echo "例如: mermaid-v1.0.0"
    echo ""
    echo "打标后，GitHub Actions 将自动创建 Release"
    exit 1
  fi
}

# 运行
main "$@"
